### ISSUE TITLE
Do we need a concept of a signal and a slot?

### ISSUE THREAD

**Issue by sensestage** [blacksound/VTM#76]
A one shot event sent out to whoever is interested in listening.

**Comment by blacksound** [comment]
Conceptually the interaction between signals and commands are similar to signals and slot in Qt.

Commands-without-arguments and Command-with-arguments may very well be two different concepts?

**Comment by pchdev** [comment]
this raises a small problem regarding SC native objects, which would not be able to have this signal-slot implementation in their definitions. Meaning that there should be a “wrapper class“ for them in order to bind the different states of the object. 
e.g SerialPort : connected / closed / error

**Comment by blacksound** [comment]
The Signal concept has been implemented in 839aa60b251169d464539279a6e0681b6ce35367.

The remaining discussion about slots continues here: #88 
So, closing this issue now.
